EXCHANGES = {
    "ADA:BTC": [
        "binance",
        "bitfinex",
        "bitstamp",
        "bittrex",
        "coinbase",
        "gateio",
        "hitbtc",
        "huobi",
        "kraken",
    ],
    "DOT:BTC": [
        "binance",
        "bitfinex",
        "bittrex",
        "coinbase",
        "gateio",
        "hitbtc",
        "huobi",
        "kraken",
        "poloniex",
    ],
    "LTC:BTC": [
        "binance",
        "bitfinex",
        "bitstamp",
        "bittrex",
        "coinbase",
        "gateio",
        "hitbtc",
        "huobi",
        "kraken",
        "poloniex",
    ],
    "SOL:BTC": [
        "binance",
        "bitfinex",
        "bittrex",
        "coinbase",
        "hitbtc",
        "huobi",
        "kraken",
        "poloniex",
    ],
    "XMR:BTC": [
        "binance",
        "bitfinex",
        "gateio",
        "hitbtc",
        "kraken",
        "poloniex",
    ],
    "ATOM:BTC": [
        "binance",
        "bittrex",
        "coinbase",
        "hitbtc",
        "huobi",
        "kraken",
        "poloniex",
        "gateio",
    ],
    "XLM:BTC": [
        "binance",
        "bitfinex",
        "bitstamp",
        "bittrex",
        "coinbase",
        "gateio",
        "hitbtc",
        "kraken",
        "poloniex",
    ],
    "ALGO:BTC": [
        "binance",
        "bitstamp",
        "bittrex",
        "coinbase",
        "hitbtc",
        "kraken",
    ],
    "FIL:BTC": [
        "binance",
        "bittrex",
        "coinbase",
        "gateio",
        "hitbtc",
        "kraken",
        "poloniex",
    ],
    "EOS:BTC": [
        "binance",
        "bitfinex",
        "bittrex",
        "coinbase",
        "gateio",
        "hitbtc",
        "huobi",
        "kraken",
        "poloniex",
    ],
    "BTC:USD": [
        "bittrex",
        "bitfinex",
        "coinbase",
        "kraken",
        "bitstamp",
    ],
    "BTC:USDT": [
        "huobi",
        "gateio",
        "mexc",
        "xtcom",
        "latoken",
        "poloniex",
        "coinex",
    ],
    "BTS:USDT": [
        "huobi",
        "gateio",
        "mexc",
        "xtcom",
        "latoken",
        "poloniex",
        "coinex",
    ],
    "XRP:BTC": [
        "bittrex",
        "binance",
        "huobi",
        "hitbtc",
        "gateio",
        "bitfinex",
        "kraken",
        "bitstamp",
    ],
    "ETH:BTC": [
        "bittrex",
        "binance",
        "poloniex",
        "huobi",
        "gateio",
        "hitbtc",
        "bitfinex",
        "coinbase",
        "kraken",
        "bitstamp",
    ],
}
